SELECT * FROM EMPLOYEES;

-- Exercise 1 on String Patterns
--- Query 1
SELECT F_NAME, L_NAME, ADDRESS FROM EMPLOYEES
	WHERE ADDRESS LIKE '%Elgin,IL';

--- Query 2
SELECT F_NAME, L_NAME, B_DATE FROM EMPLOYEES
	WHERE B_DATE LIKE '197%';
	
--- Query 3
SELECT F_NAME, L_NAME, DEP_ID, SALARY FROM EMPLOYEES
	WHERE DEP_ID = 5
	AND SALARY 
		BETWEEN 60000 AND 70000;

-- Exercise 2 on Sorting
--- Query 1
SELECT * FROM EMPLOYEES
	ORDER BY DEP_ID;
	
--- Query 2
SELECT * FROM EMPLOYEES
	ORDER BY DEP_ID DESC, L_NAME DESC;
	
--- Query 3
SELECT D.DEP_NAME , E.F_NAME, E.L_NAME
	FROM EMPLOYEES as E, DEPARTMENTS as D
	WHERE E.DEP_ID = D.DEPT_ID_DEP -- -> DEPT_ID_DEP is the ID column in the DEPARTMENTS table!
	ORDER BY D.DEP_NAME, E.L_NAME DESC;
	
-- Exercise 3 on GROUPING
--- Query 1
SELECT DEP_ID, COUNT(EMP_ID) as NU_EMP FROM EMPLOYEES 
	GROUP BY DEP_ID;
	
--- Query 2 & 3
SELECT DEP_ID, COUNT(EMP_ID) as NUM_EMPLOYEES, AVG(SALARY) as AVG_SLRY FROM EMPLOYEES 
	GROUP BY DEP_ID;
	
--- Query 4
SELECT DEP_ID, COUNT(EMP_ID) as NUM_EMPLOYEES, AVG(SALARY) as AVG_SLRY FROM EMPLOYEES 
	GROUP BY DEP_ID
	ORDER BY AVG_SLRY;
	
--- Query 5
SELECT DEP_ID, COUNT(EMP_ID) as NUM_EMPLOYEES, AVG(SALARY) as AVG_SLRY FROM EMPLOYEES 
	GROUP BY DEP_ID
		HAVING COUNT(EMP_ID) < 4 -- -> NUM_EMPLOYEES can not be used here, the number has to be calculated again.
	ORDER BY AVG_SLRY;